ALLOW_MAIN_MEMU="True"

# "azure" or "openai"
OPENAI_API_TYPE="openai"

[open_api_azure]
AZURE_OPENAI_API_KEY="xxx"
OPENAI_API_VERSION="2023-03-15-preview"
AZURE_OPENAI_ENDPOINT="https://ai-proxy.lab.epam.com"
OPENAI_API_DEPLOYMENT="gpt-4o-mini-2024-07-18"

[open_api_openai]
OPENAI_API_KEY="xxx"
